### ISSUE TITLE
version 6.2 required by mkdocs-material

### ISSUE THREAD

**Issue by pkestene** [conda-forge/pymdown-extensions-feedstock#9]
conda-forge package [mkdocs-material](https://github.com/conda-forge/mkdocs-material-feedstock) has the following requirement:

```shell
Requires-Dist: pymdown-extensions (<6.3,>=6.2)
```

Would it be possible to have `pymdown-extensions` version 6.2 ? before `mkdocs-material` gets updated to be able to use `pymdown-extensions` `>= 7.0`

Thank you.

**Comment by ewels** [comment]
Hi @pkestene,

That's a great question! I'm fairly used to updating conda-forge packages to the latest version, but I'm not sure about how to build a specific older archived version. At least not without that becoming the new default for everyone..

@conda-forge/core - any pointers on how to go about doing this? I had a quick google but couldn't find anything specifically on this topic.

Thanks.

Phil

**Comment by beckermr** [comment]
You can build older versions by making PRs into a branch ont he main repo.

Note that the version in the env is set by the conda solver which prefers newer versions. It is not set by the version on the master branch.

**Comment by ewels** [comment]
ok great, so it's the same as a regular update release? Good to know - thanks for the fast response 👍

**Comment by pkestene** [comment]
thanks for your reactivity; this looks on the way to be solved.

**Comment by ewels** [comment]
Unfortunately this isn't going very smoothly. The build is failing due to missing the [pep562](https://pypi.org/project/pep562/) package. I tried adding it in as a run time requirement, but it's not found on any conda channels.

I'm not sure that it's worth creating a totally new conda-forge package (even if it is from PyPI) just to satisfy a dependency for an outdated version of another package.

Is there a reason that you can't use / update to the latest version of [mkdocs-material](https://github.com/conda-forge/mkdocs-material-feedstock) instead? That would probably be quite a lot easier and better for the community. It looks like the conda version has fallen quite a long way behind PyPI (latest `4.5`, PyPI has `5.1.6`).

Where did you find the `pymdown-extensions (<6.3,>=6.2)` dependency by the way? The latest version of `mkdocs-material` seems to [only require](https://github.com/conda-forge/mkdocs-material-feedstock/blob/a21b488e690e2b0df41a1ea850f79cf62526d37e/recipe/meta.yaml#L25) `pymdown-extensions >=4.11`

Phil

**Comment by pkestene** [comment]
all I did today, is `conda install -c conda-forge mkdocs mkdocs-material` in miniconda3 env, and it installed mkdocs-material-4.5.0-py_0 and its METADATA file says:

```shell
Requires-Dist: mkdocs (>=1)
Requires-Dist: mkdocs-minify-plugin (>=0.2)
Requires-Dist: Pygments (>=2.2)
Requires-Dist: markdown (<3.2)
Requires-Dist: pymdown-extensions (<6.3,>=6.2)
```

so I don't really understand what is going here ?
Usually installing package from conda-forge is very smooth....

**Comment by ewels** [comment]
Strange! I don't really understand either. But as you say, I think moving forwards is the best approach so I'll close this issue and the PR now.

> But it looks like newer mkdocs-material depends upon mkdocs-material-extensions for which a conda-recipe does not exist yet.

Yes - this is the rabbit hole you end up with sometimes! That's the only reason that I'm a maintainer for this package: I needed it to be updated because it was a dependency for another that I wanted. But it benefits everyone in the end if you can help keep packages up to date 😄 

Phil
